### ISSUE TITLE
Section 0 shows description if standard title is checked

### ISSUE THREAD

**Issue by Kathrin84** [mudrd8mz/moodle-block_course_contents#17]
Hi David,

a teacher told us about this bug.
Section 0 has a standard title that's used (General). It is checked by default. If the teacher keeps this setting and adds a description to the section 0, your block shows the whole description as the section title:
![beschreibung_als_ueberschrift](https://cloud.githubusercontent.com/assets/4711883/14487765/d35b3d50-0164-11e6-9178-f7b30f827bb8.png)

If the description is deleted OR the checkbox is disabled and a own title is typed, the block uses the section title as it should:
![keine_beschreibung](https://cloud.githubusercontent.com/assets/4711883/14487813/0aab7798-0165-11e6-9b92-934e58613aba.png)

We're using Moodle 3.03+ and it's happening in our own theme as well as in 'More' and 'Clean' theme.

Cheers,
Kathrin

**Comment by mudrd8mz** [comment]
Hi Kathrin. If I understand the description correctly, then it is actually expected behaviour. The block has been designed and implemented in older versions of Moodle when sections did not have own editable titles yet. Teachers often put the section title as a first line of the section description. And the block takes and uses this first line as the section title.

When the section titles feature had been added to Moodle, the block behaviour was modified so that:

* If a section has a custom title defined, it is preferred.
* If the default section title is to be displayed (such as "General" or "Topic 1"), then it falls back to the original behaviour and uses the first line of the description as the title.

I can see now that it might help to have the behaviour more configurable so that the block would read the first line of the description only when set so. Meanwhile, your teacher may want to somehow visually highlight the first part of the section description so that it is used as a title. For example, something like this could help:

    <p><strong>Herzlich willkommen</strong> im leeren Testkurs. ... (continues) </p>

In this case, the block should use just the "Herzlich willkommen" as the title.

More explanation available at https://docs.moodle.org/en/Course_contents_block

**Comment by mudrd8mz** [comment]
Thanks @Kathrin84 for the pull request. Unfortunately I can't accept it as it is now without a bit more work.

(1) I did not find a way how to actually set those new global configuration. Am I missing something? How did you test the added settings.php file? I expected the patch would add the `has_config()` method to the block class.

(2) When attempting to edit a block instance, I am seeing buch of PHP notices:

```
Notice: Undefined property: stdClass::$admin_lock_blocktitle in blocks/course_contents/edit_form.php on line 40

Notice: Undefined property: stdClass::$admin_lock_blocktitle in blocks/course_contents/edit_form.php on line 46

Notice: Undefined property: stdClass::$admin_lock_defaultsectiontitle in blocks/course_contents/edit_form.php on line 53

Notice: Undefined property: stdClass::$admin_defaultsectiontitle in blocks/course_contents/edit_form.php on line 56

Notice: Undefined property: stdClass::$admin_lock_enumerate in blocks/course_contents/edit_form.php on line 60
```

(3) Can the coding style please follow the Moodle coding style guidelines as documented at https://docs.moodle.org/dev/Coding_style There are tools available to help to check that.

(4) The new properties should better be named like `lockblocktitle` rather than `admin_lock_blocktitle`

(5) I would generally prefer if your patch naturally fits the place it changes. All the little inconsistencies like double quotes for some (yet not all) strings do not look good.

Thanks in advance.

**Comment by mudrd8mz** [comment]
In the version 4.0 of the block, the instances can be configured so that this auto-title feature is not happening.
